language: php

php:
  - 5.4
  - 5.5
  - 5.6

services:
  - mysql

sudo: false

env:
#  - PHALCON_VERSION="2.1.x"
  - PHALCON_VERSION="2.0.x"
  - PHALCON_VERSION="phalcon-v2.0.9"

before_install:
  - composer self-update
  - travis_retry composer install --prefer-source

before_script:
  - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b ${PHALCON_VERSION}
  - (cd cphalcon/ext; export CFLAGS="-g0 -O0 -std=gnu90"; phpize &> /dev/null && ./configure --silent --enable-phalcon &> /dev/null && make --silent -j2 &> /dev/null && make --silent install && phpenv config-add ../unit-tests/ci/phalcon.ini &> /dev/null)
  - php --ri phalcon
  - echo 'create database valid charset=utf8mb4 collate=utf8mb4_unicode_ci;' | mysql -u root
  - cat tests/dist/schema.sql | mysql valid -u root

script:
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-text
